<?php

namespace controlBundle\Repository;

/**
 * plantillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plantillaRepository extends \Doctrine\ORM\EntityRepository
{
}
